{{- if .Values.postgresdb.postgresdbInternal.enabled | default false }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "gel.postgres.name" . }}
  labels:
    {{- include "gel.postgres.labels" . | nindent 4 }}
spec:
  description: {{ .Values.postgresdb.postgresdbInternal.description | default "postgres cluster"}}
  imageName: {{ .Values.postgresdb.postgresdbInternal.image }}
  instances: {{ .Values.postgresdb.postgresdbInternal.instances }}
  superuserSecret:
    name: {{ include "gel.postgres.name" . }}-auth
  enableSuperuserAccess: {{ .Values.postgresdb.postgresdbInternal.enableAdminAccess }}
  startDelay: {{ .Values.postgresdb.postgresdbInternal.startDelay }}
  stopDelay: {{ .Values.postgresdb.postgresdbInternal.stopDelay }}
  primaryUpdateStrategy: {{ .Values.postgresdb.postgresdbInternal.primaryUpdateStrategy }}
  logLevel: {{ .Values.postgresdb.postgresdbInternal.logLevel }}
  {{- if .Values.postgresdb.postgresdbInternal.priorityClassName }}
  priorityClassName: {{ .Values.postgresdb.postgresdbInternal.priorityClassName }}
  {{- end }}
  bootstrap:
    initdb:
      database: {{ .Values.postgresdb.postgresdbInternal.database | default "gel" }}
      owner: {{ .Values.postgresdb.postgresdbInternal.owner | default "postgres" }}
      secret:
        name: {{ include "gel.postgres.name" . }}-auth
  {{- with .Values.postgresdb.postgresdbInternal.storage }}
  storage:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  postgresql:
    {{- with .Values.postgresdb.postgresdbInternal.parameters }}
    parameters:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.postgresdb.postgresdbInternal.pghba }}
    pg_hba:
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.postgresdb.postgresdbInternal.plugins }}
  plugins:
    {{- toYaml .Values.postgresdb.postgresdbInternal.plugins | nindent 4 }}
  {{- end }}
{{- end }}