{{- if and .Values.postgresdb.postgresdbInternal.enabled .Values.postgresdb.postgresdbInternal.objectStore.enabled .Values.postgresdb.postgresdbInternal.objectStore.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresdb.postgresdbInternal.objectStore.secret.name }}
  labels:
    {{- include "gel.postgres.labels" . | nindent 4 }}
type: Opaque
data:
  ACCESS_KEY_ID: {{ .Values.postgresdb.postgresdbInternal.objectStore.secret.accessKeyId | b64enc }}
  ACCESS_SECRET_KEY: {{ .Values.postgresdb.postgresdbInternal.objectStore.secret.secretAccessKey | b64enc }}
{{- end }}

