apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gel.fullname" . }}
  annotations:
    {{- if .Values.postgresdb.postgresdbInternal.enabled | default false }}
    helm.sh/hook-weight: "2"
    helm.sh/hook-requires: gel-db
    {{- end }}
    {{- with .Values.gel.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "gel.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoScaling.enabled }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "gel.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gel.labels" . | nindent 8 }}
    spec:
      {{- if .Values.serviceAccount.create | default false }}
      serviceAccountName: {{ include "gel.serviceAccountName" . }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- if .Values.postgresdb.postgresdbInternal.enabled | default false }}
      initContainers:
      - name: wait-for-postgres
        image: busybox
        command: ['sh', '-c', 'until nc -z {{ include "gel.postgres.name" . }}-rw 5432; do echo waiting for postgres; sleep 2; done;']
      {{- end }}
      containers:
      - name: {{ include "gel.fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- with .Values.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- if .Values.startupProbe.enabled }}
        startupProbe:
          httpGet:
            path: /server/status/alive
            port: {{ .Values.service.port }}
          initialDelaySeconds: {{ .Values.startupProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.startupProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.startupProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.startupProbe.failureThreshold }}
        {{- end }}
        {{- if .Values.readinessProbe.enabled }}
        readinessProbe:
          httpGet:
            path: /server/status/ready
            port: {{ .Values.service.port }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
        {{- end }}
        {{- if .Values.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            path: /server/status/alive
            port: {{ .Values.service.port }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
        {{- end }}
        ports:
        - containerPort: 5656
        volumeMounts:
        {{- if and (not .Values.postgresdb.postgresdbInternal.enabled) (not .Values.postgresdb.postgresdbExternal.enabled) }}
        - name: gel-data
          mountPath: /var/lib/gel/data
        {{- end }}
        {{- if .Values.tls.enabled }}
        - name: tls-cert
          mountPath: /etc/gel/tls
          readOnly: true
        {{- end }}
        envFrom:
        - secretRef:
            name: {{ include "gel.fullname" . }}-auth
        {{- if or .Values.postgresdb.postgresdbInternal.enabled .Values.postgresdb.postgresdbExternal.enabled }}
        - secretRef:
            name: {{ include "gel.fullname" . }}-backend
        {{- end }}
        env:
        - name: GEL_SERVER_ADMIN_UI
          value: {{ .Values.gel.adminUI | default "enabled" }}
        {{- if .Values.tls.enabled }}
        - name: GEL_SERVER_TLS_CERT_FILE
          value: /etc/gel/tls/tls.crt
        - name: GEL_SERVER_TLS_KEY_FILE
          value: /etc/gel/tls/tls.key
        {{- end }}
        - name: GEL_DOCKER_LOG_LEVEL
          value: {{ .Values.gel.logLevel | default "info" }}
        - name: GEL_SERVER_DEFAULT_AUTH_METHOD
          value: {{ .Values.gel.defaultAuthMethod | default "SCRAM" }}
        - name: GEL_SERVER_HTTP_ENDPOINT_SECURITY
          value: {{ .Values.gel.httpEndpointSecurity | default "tls" }}
        {{- if .Values.gel.serverSecurity }}
        - name: GEL_SERVER_SECURITY
          value: {{ .Values.gel.serverSecurity }}
        {{- end }}
        - name: GEL_SERVER_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: GEL_PORT
          value: {{ .Values.service.port | quote }}
        - name: GEL_INSTANCE_NAME
          value: {{ include "gel.fullname" . }}
        {{- if .Values.tls.enabled }}
        - name: GEL_SERVER_TLS_CERT_MODE
          value: require_file
        {{- else }}
        - name: GEL_SERVER_TLS_CERT_MODE
          value: generate_self_signed
        {{- end }}
      volumes:
      {{- if .Values.tls.enabled }}
      - name: tls-cert
        secret:
          secretName: {{ include "gel.fullname" . }}-tls-cert
      {{- end }}
      {{- if and (not .Values.postgresdb.postgresdbInternal.enabled) (not .Values.postgresdb.postgresdbExternal.enabled) }}
      - name: gel-data
        persistentVolumeClaim:
          claimName: {{ include "gel.fullname" . }}-data
      {{- end }} 
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
